[env:m5stack-cardputer-adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -O2

lib_deps =
    m5stack/M5Cardputer@^1.1.1
    m5stack/M5Unified@^0.2.17
    m5stack/M5GFX@^0.2.17

upload_speed = 921600
monitor_speed = 115200

board_build.partitions = huge_app.csv
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
